FitnessCenter.WEB/Controllers/AncillaryController.cs
using FitnessCenter.CrossCutting.Ancillary;
using FitnessCenter.CrossCutting.Enumerations;
using System.Web.Mvc;

namespace FitnessCenter.WEB.Controllers
{
    public class AncillaryController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeLanguage(LanguageEnum selectedLanguage, string returnUrl)
        {
            Culture.Set(selectedLanguage);

            return RedirectToLocal(returnUrl);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FitnessCenter.WEB/Controllers/GroupController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Enumerations;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.WEB.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using static System.String;

namespace FitnessCenter.WEB.Controllers
{
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class GroupController : Controller
    {
        private readonly IClientService<ClientDTO> clientService;
        private readonly IGroupService<GroupDTO> groupService;
        private readonly IUserService<UserDTO, string> userService;

        public GroupController(
            IClientService<ClientDTO> clientService,
            IGroupService<GroupDTO> groupService,
            IUserService<UserDTO, string> userService
        )
        {
            this.clientService = clientService;
            this.groupService = groupService;
            this.userService = userService;
        }

        public async Task<ActionResult> GetGroup(int groupId)
        {
            var groupDTO = await groupService.FindAsync(new GroupDTO { Id = groupId });

            var model = Mapper.Map<GroupViewModel>(groupDTO);
            model.IsAuthenticatedUser = User.Identity.IsAuthenticated;

            if (IsNullOrEmpty(User.Identity.Name))
            {
                return View(model);
            }

            UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
            if (userDTO == null)
            {
                return View(model);
            }

            var clientDTOs = clientService.Find(clientDTO => clientDTO.GroupId == groupDTO.Id && clientDTO.UserId == userDTO.Id);
            model.IsUserInGroup = clientDTOs.Count > 0;

            return View(model);
        }

        public ActionResult GetActualGroups(int page = 0)
        {
            var numberOfGroupsForDisplay = (int)AppConstantsEnum.NumberOfGroupsForDisplay;
            var actualGroupsForDisplay = groupService
                .GetAllActual()
                .OrderBy(x => x.Name)
                .Skip(page * numberOfGroupsForDisplay)
                .Take(numberOfGroupsForDisplay);

            return View(Mapper.Map<ICollection<GroupViewModel>>(actualGroupsForDisplay));
        }

        public ActionResult GetActualGroupsPagination()
        {
            return View((int)Math.Ceiling((groupService.GetAllActual()?.Count ?? 0) / (double)AppConstantsEnum.NumberOfGroupsForDisplay));
        }
    }
}

FitnessCenter.WEB/Controllers/MessageController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Ancillary;
using FitnessCenter.CrossCutting.Enumerations;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.CrossCutting.Resources;
using FitnessCenter.WEB.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using static System.DateTime;
using static System.String;

namespace FitnessCenter.WEB.Controllers
{
    [Authorize]
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class MessageController : Controller
    {
        private readonly IIncomingMessageService<IncomingMessageDTO> incomingMessageService;
        private readonly IOutgoingMessageService<OutgoingMessageDTO> outgoingMessageService;
        private readonly IUserService<UserDTO, string> userService;

        public MessageController
        (
            IIncomingMessageService<IncomingMessageDTO> incomingMessageService,
            IOutgoingMessageService<OutgoingMessageDTO> outgoingMessageService,
            IUserService<UserDTO, string> userService
        )
        {
            this.incomingMessageService = incomingMessageService;
            this.outgoingMessageService = outgoingMessageService;
            this.userService = userService;
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public ActionResult Index(MessageTypeEnum messageType = MessageTypeEnum.Inbox)
        {
            return View(messageType);
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public ActionResult Compose()
        {
            return View(new ComposeMessageViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(RoleEnum.User))]
        public async Task<ActionResult> Compose(ComposeMessageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var resultOfCompose = new ResultOfCompose
            {
                IsSuccess = false,
                Message = Resource.MessageNotSent
            };

            try
            {
                if (IsNullOrEmpty(User.Identity.Name) || IsNullOrEmpty(model.DestinationEmail))
                {
                    return RedirectToAction("ShowResultOfCompose", resultOfCompose);
                }

                UserDTO currentUserDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                UserDTO destinationUserDTO = await userService.FindAsync(new UserDTO { Email = model.DestinationEmail });
                if (currentUserDTO == null || destinationUserDTO == null)
                {
                    return RedirectToAction("ShowResultOfCompose", resultOfCompose);
                }

                model.UserId = currentUserDTO.Id;
                model.SentDate = Now;
                var outgoingMessageDTO = Mapper.Map<OutgoingMessageDTO>(model);

                OperationDetails operationDetails = await outgoingMessageService.CreateAsync(outgoingMessageDTO);
                if (!operationDetails.IsSucceeded)
                {
                    return RedirectToAction("ShowResultOfCompose", resultOfCompose);
                }

                var outgoingMessageDTOs = outgoingMessageService.Find(message => message.UserId == outgoingMessageDTO.UserId && message.Title == outgoingMessageDTO.Title && message.Text == outgoingMessageDTO.Text);
                if (outgoingMessageDTOs.Count == 0)
                {
                    return RedirectToAction("ShowResultOfCompose", resultOfCompose);
                }

                operationDetails = await incomingMessageService.CreateAsync(new IncomingMessageDTO
                {
                    UserId = destinationUserDTO.Id,
                    OutgoingMessageId = outgoingMessageDTOs.Max(message => message.Id),
                    ReadDate = null
                });
                if (!operationDetails.IsSucceeded)
                {
                    return RedirectToAction("ShowResultOfCompose", resultOfCompose);
                }

                resultOfCompose.IsSuccess = true;
                resultOfCompose.Message = Resource.MessageSent;
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return RedirectToAction("ShowResultOfCompose", resultOfCompose);
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public ActionResult ShowResultOfCompose(ResultOfCompose model)
        {
            return View(model);
        }

        [AllowAnonymous]
        public async Task<ActionResult> GetCountUnreadMessages()
        {
            if (IsNullOrEmpty(User.Identity.Name))
            {
                return View(0);
            }

            UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
            if (userDTO == null)
            {
                return View(0);
            }

            var incomingMessageDTOs = incomingMessageService.Find(message => message.UserId == userDTO.Id && !message.ReadDate.HasValue);

            return View(incomingMessageDTOs.Count);
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public async Task<ActionResult> GetIncomingMessages()
        {
            if (IsNullOrEmpty(User.Identity.Name))
            {
                return RedirectToAction("Forbidden", "Error");
            }
            UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
            if (userDTO == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            var model = new List<IncomingMessageViewModel>();
                
            var incomingMessageDTOs = incomingMessageService.Find(incomingMessage => incomingMessage.UserId == userDTO.Id);
            if (incomingMessageDTOs.Count == 0)
            {
                return View(model);
            }
            var outgoingMessageDTOs = outgoingMessageService.Find(outgoingMessage => incomingMessageDTOs.Select(incomingMessage => incomingMessage.OutgoingMessageId).Contains(outgoingMessage.Id));
            if (outgoingMessageDTOs.Count != incomingMessageDTOs.Count)
            {
                return View(model);
            }

            model = Mapper.Map<List<IncomingMessageViewModel>>(incomingMessageDTOs);
            model.ForEach(incomingMessage => 
            {
                incomingMessage.OutgoingMessage = Mapper.Map<OutgoingMessageViewModel>(outgoingMessageDTOs.Where(outgoingMessage => outgoingMessage.Id == incomingMessage.OutgoingMessageId).FirstOrDefault());
            });

            return View
            (
                model
                    .OrderByDescending(incomingMessage => incomingMessage.OutgoingMessage.SentDate)
                    .ToList()
            );
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public async Task<ActionResult> GetOutgoingMessages()
        {
            if (IsNullOrEmpty(User.Identity.Name))
            {
                return RedirectToAction("Forbidden", "Error");
            }
            UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
            if (userDTO == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            var model = new List<OutgoingMessageViewModel>();
            var outgoingMessageDTOs = outgoingMessageService.Find(message => message.UserId == userDTO.Id);
            if (outgoingMessageDTOs.Count == 0)
            {
                return View(model);
            }
            model = Mapper.Map<List<OutgoingMessageViewModel>>(outgoingMessageDTOs);
            model.ForEach(outgoingMessage => 
            {
                var incomingMessageDTOs = incomingMessageService.Find(message => message.OutgoingMessageId == outgoingMessage.Id);
                outgoingMessage.IncomingMessages = Mapper.Map<List<IncomingMessageViewModel>>(incomingMessageDTOs);
            });

            return View
            (
                model
                    .Where(outgoingMessage => outgoingMessage.IncomingMessages != null && outgoingMessage.IncomingMessages.Count > 0)
                    .OrderByDescending(outgoingMessage => outgoingMessage.SentDate)
                    .ToList()
            );
        }

        [Authorize(Roles = nameof(RoleEnum.User))]
        public async Task MarkMessageAsRead(int messageId)
        {
            var incomingMessageDTO = await incomingMessageService.FindAsync(new IncomingMessageDTO { Id = messageId });
            incomingMessageDTO.ReadDate = Now;
            await incomingMessageService.UpdateAsync(incomingMessageDTO);
        }
    }
}

FitnessCenter.WEB/Controllers/UserController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Ancillary;
using FitnessCenter.CrossCutting.Enumerations;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.CrossCutting.Resources;
using FitnessCenter.WEB.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static System.String;

namespace FitnessCenter.WEB.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService<UserDTO, string> userService;

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public UserController(IUserService<UserDTO, string> userService)
        {
            this.userService = userService;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Login(string returnUrl)
        {
            if (!IsNullOrEmpty(User.Identity.Name))
            {
                UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                if (userDTO != null)
                {
                    return RedirectToLocal(returnUrl);
                }
            }

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return await Login(Mapper.Map<UserDTO>(model), () => RedirectToLocal(returnUrl), () => View(model));
        }

        [AllowAnonymous]
        public async Task<ActionResult> Register(string returnUrl)
        {
            if (!IsNullOrEmpty(User.Identity.Name))
            {
                UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                if (userDTO != null)
                {
                    return RedirectToLocal(returnUrl);
                }
            }

            PrepareLanguagesSelectList();
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model, HttpPostedFileBase postedFile)
        {
            if (!ModelState.IsValid)
            {
                PrepareLanguagesSelectList();
                return View(model);
            }

            UserDTO userDTO = Mapper.Map<UserDTO>(model);
            userDTO.Photo = GetFile(postedFile);
            userDTO.IsBlocked = false;

            OperationDetails operationDetails = await userService.CreateAsync(userDTO);
            if (!operationDetails.IsSucceeded)
            {
                ModelState.AddModelError(Empty, operationDetails.Message);
                PrepareLanguagesSelectList();
                return View(model);
            }
            await userService.AddToRoleAsync(userDTO, RoleEnum.User);

            return await Login(userDTO, () => RedirectToAction("Index", "Home"), () => 
            {
                PrepareLanguagesSelectList();
                return View(model);
            });
        }

        public ActionResult LogOff()
        {
            Culture.Set(LanguageEnum.English);
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private byte[] GetFile(HttpPostedFileBase postedFile)
        {
            if (postedFile == null)
            {
                return null;
            }

            using (var binaryReader = new BinaryReader(postedFile.InputStream))
            {
                return binaryReader.ReadBytes(postedFile.ContentLength);
            }
        }

        private void PrepareLanguagesSelectList()
        {
            SelectList languages = new SelectList
            (
                Enum.GetNames(typeof(LanguageEnum)).Where(language => !language.Contains("Default"))
            );
            ViewBag.Languages = languages;
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private async Task<ActionResult> Login(UserDTO userDto, Func<ActionResult> successfulAction, Func<ActionResult> unsuccessfulAction)
        {
            ClaimsIdentity claimsIdentity = await userService.AuthenticateAsync(userDto);
            if (claimsIdentity == null)
            {
                ModelState.AddModelError(Empty, Resource.UnsuccessfulLoginAttempt);
                return unsuccessfulAction();
            }
            AuthenticationManager.SignOut();
            AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = true }, claimsIdentity);

            UserDTO authenticatedUserDTO = await userService.FindAsync(userDto);
            Culture.Set(authenticatedUserDTO.Language);

            return successfulAction();
        }
    }
}

FitnessCenter.WEB/Views/Shared/ComposePageNavigation.cshtml
@using FitnessCenter.CrossCutting.Enumerations
@using FitnessCenter.CrossCutting.Resources

<ul id="messagesPills" class="nav nav-pills flex-md-column">
    <li id="composeLink" class="nav-item">
        @Html.ActionLink(Resource.Compose, "Compose", "Message", new { @class = "nav-link text-bold active" })
    </li>
    <li class="nav-item">
        @Html.ActionLink(Resource.Inbox, "Index", "Message", new { messageType = MessageTypeEnum.Inbox }, new { @class = "nav-link" })
    </li>
    <li class="nav-item">
        @Html.ActionLink(Resource.Sent, "Index", "Message", new { messageType = MessageTypeEnum.Sent }, new { @class = "nav-link" })
    </li>
</ul>

FitnessCenter.WEB/Views/Shared/FooterLeft.cshtml
@using FitnessCenter.CrossCutting.Resources

&copy; @DateTime.Now.Year <span class="text-bold"><span class="accent">@Resource.Rokhlikov</span> @Resource.Artur @Resource.Mikhailovich</span>
<ul class="list-border-left navigation text-small-italic">
    <li>docto-RAM&#64;yandex&#46;ru</li>
    <li>+375 (33) 632-25-49</li>
    <li><a href="https://www.linkedin.com/in/docto-RAM" target="_blank">www.LinkedIn.com/in/docto-RAM</a></li>
</ul>

FitnessCenter.WEB/Views/Shared/FooterRight.cshtml
@using FCA = FitnessCenter.CrossCutting.Ancillary
@using FitnessCenter.CrossCutting.Enumerations

@{
    SelectList languages = new SelectList
    (
        Enum.GetNames(typeof(LanguageEnum)).Where(language => !language.Contains("Default")),
        FCA.Culture.GetLanguage().ToString()
    );
}

@using (Html.BeginForm("ChangeLanguage", "Ancillary", FormMethod.Post, new { @id = "languageSelectionForm", @role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.Hidden("returnUrl", ViewContext.HttpContext.Request.Url.PathAndQuery)
    <div class="container">
        <div class="row">
            <div class="form-group">
                @Html.DropDownList("selectedLanguage", languages, new { @id = "selectedLanguage", @class = "form-control" })
            </div>
        </div>
    </div>
}

FitnessCenter.WEB/Views/Shared/Group.cshtml
@using FitnessCenter.WEB.ViewModels

@model  GroupViewModel

@{
    Layout = null;
}

@{
    var isCompleteGroup = Model.MaxNumberOfPeople.HasValue && Model.Clients.Count >= Model.MaxNumberOfPeople.Value;
}

@helper GetGroupHeader()
{
    var schedules = Model.Schedules.Where(x => x.EndTime > DateTime.Now);
    <strong>@Model.Name</strong>
    <br />
    <span class="group-head-date">
        @((schedules.Count() == 1) ? $"({schedules.FirstOrDefault().BeginTime.ToShortDateString()})" : $"({schedules.Min(x => x.BeginTime).ToShortDateString()} - {schedules.Max(x => x.BeginTime).ToShortDateString()})")
    </span>
}

@if (Model != null)
{
    <div class="group-head-@((isCompleteGroup) ? "complete" : "incomplete")">
        @if (isCompleteGroup || !Model.IsEnabledLinks)
        {
            @GetGroupHeader()
        }
        else
        {
            <a value="@Model.Id">
                @GetGroupHeader()
            </a>
        }
    </div>
    <div class="group-body">
        @Html.DisplayFor(model => model.Schedules, "Schedules")
    </div>
}

FitnessCenter.WEB/Views/Shared/GroupCost.cshtml
@using FitnessCenter.WEB.ViewModels

@model  GroupViewModel

<div>
    @Html.LabelFor(model => model.Cost)
    <div class="text-accent">
        @Html.DisplayFor(model => model.Cost)
    </div>
</div>

FitnessCenter.WEB/Views/Shared/HeaderCenter.cshtml
<img src="@Url.Content("~/FrontEnd/src/assets/images/head.jpg")" width="432" />

FitnessCenter.WEB/Views/Shared/HeaderLeft.cshtml
@Html.Raw(@Html.ActionLink("Fitness Center", "Index", "Home").ToHtmlString().Replace("Fitness Center", $"<img src=\"{Url.Content("~/FrontEnd/src/assets/images/logo.jpg")}\" width=\"134\" />"))

FitnessCenter.WEB/Views/Shared/HeaderRight.cshtml
@using FitnessCenter.CrossCutting.Resources

<ul class="navigation navigation-header">
    @if (Request.IsAuthenticated)
    {
        <li>
            @User.Identity.Name
        </li>
        <li>
            @Html.ActionLink(Resource.Messages, "Index", "Message") <span id="countUnreadMessages"></span>
        </li>
        <li>
            @Html.ActionLink(Resource.LogOff, "LogOff", "User")
        </li>
    }
    else
    {
        <li>
            @Html.ActionLink(Resource.LogIn, "Login", "User")
        </li>
        <li>
            @Html.ActionLink(Resource.JoinFitness, "Register", "User")
        </li>
    }
</ul>

FitnessCenter.WEB/Views/Shared/Layout.cshtml
@using FitnessCenter.CrossCutting.Resources

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>@($"{ViewBag.Title}{((ViewBag.Title == null) ? "" : " - ")}{Resource.FitnessCenter}")</title>
    @Styles.Render("~/bundles/assets/styles")
    @Scripts.Render("~/bundles/js/modernizr")
</head>
<body>
    <div id="loader"></div>
    <header>
        <div class="container">
            <div class="row">
                <div class="headerLeft col-6 col-md-8 col-lg-3 col-xl-2">
                    @Html.Partial("HeaderLeft")
                </div>
                <div class="headerCenter col-lg-6 col-xl-7 d-none d-lg-block">
                    @Html.Partial("HeaderCenter")
                </div>
                <div class="headerRight col-6 col-md-4 col-lg-3 col-xl-3">
                    @Html.Partial("HeaderRight")
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="main col-12">
                    @RenderSection("Main", required: false)
                </div>
            </div>
            <div class="row">
                <div class="body col-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="container">
            <div class="row">
                <div class="footerLeft col-9 col-md-10">
                    @Html.Partial("FooterLeft")
                </div>
                <div class="footerRight col-3 col-md-2">
                    @Html.Partial("FooterRight")
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-indent-big">
                    <div class="notification">
                        @Resource.YouAreOnADemoResource
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @Html.Partial("UrlManager")
    @Scripts.Render("~/bundles/js/jquery")
    @Scripts.Render("~/bundles/js/bootstrap")
    @Scripts.Render("~/bundles/js")
    @RenderSection("Scripts", required: false)
</body>
</html>

FitnessCenter.WEB/Views/Shared/UrlManager.cshtml
<script>
    UrlManager = {
        groupGetGroupUrl: '@Url.Action("GetGroup", "Group")',
        groupGetActualGroupsUrl: '@Url.Action("GetActualGroups", "Group")',
        groupGetActualGroupsPaginationUrl: '@Url.Action("GetActualGroupsPagination", "Group")',
        messageGetCountUnreadMessagesUrl: '@Url.Action("GetCountUnreadMessages", "Message")',
        messageGetIncomingMessagesUrl: '@Url.Action("GetIncomingMessages", "Message")',
        messageGetOutgoingMessagesUrl: '@Url.Action("GetOutgoingMessages", "Message")',
        messageMarkMessageAsReadUrl: '@Url.Action("MarkMessageAsRead", "Message")',
        trainerGetGroupUrl: '@Url.Action("GetGroup", "Trainer")'
    };
</script>