FitnessCenter.WEB/Controllers/HomeController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.WEB.ViewModels;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;

namespace FitnessCenter.WEB.Controllers
{
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class HomeController : Controller
    {
        IUserService<UserDTO, string> userService;

        public HomeController(IUserService<UserDTO, string> userService)
        {
            this.userService = userService;
        }

        public async Task<ActionResult> Index()
        {
            var model = default(UserViewModel);

            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                    if (user == null)
                    {
                        return RedirectToAction("NotFound", "Error");
                    }

                    model = Mapper.Map<UserViewModel>(user);
                    model.Roles = userService.GetRoles(user).OrderBy(x => x.ToString());
                }
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return View(model);
        }
    }
}

FitnessCenter.WEB/Controllers/Roles/AdministratorController.cs
using FitnessCenter.CrossCutting.Enumerations;
using System.Web.Mvc;
using System.Web.UI;

namespace FitnessCenter.WEB.Controllers.Roles
{
    [Authorize]
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class AdministratorController : Controller
    {
        [Authorize(Roles = nameof(RoleEnum.Administrator))]
        public ActionResult Index()
        {
            return View();
        }
    }
}

FitnessCenter.WEB/Controllers/Roles/ClientController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Ancillary;
using FitnessCenter.CrossCutting.Enumerations;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.WEB.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using static System.DateTime;
using static System.String;

namespace FitnessCenter.WEB.Controllers.Roles
{
    [Authorize]
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class ClientController : Controller
    {
        private readonly IClientService<ClientDTO> clientService;
        private readonly IGroupService<GroupDTO> groupService;
        private readonly IUserService<UserDTO, string> userService;

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ClientController
        (
            IClientService<ClientDTO> clientService,
            IGroupService<GroupDTO> groupService,
            IUserService<UserDTO, string> userService
        )
        {
            this.clientService = clientService;
            this.groupService = groupService;
            this.userService = userService;
        }

        [Authorize(Roles = nameof(RoleEnum.Client))]
        public async Task<ActionResult> Index()
        {
            var currentClientsModel = new List<CurrentClientViewModel>();

            try
            {
                if (IsNullOrEmpty(User.Identity.Name))
                {
                    return RedirectToAction("InternalServerError", "Error");
                }

                var userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                if (userDTO == null)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                var clientDTOs = clientService.Find(x => x.UserId == userDTO.Id);
                if (clientDTOs.Count == 0)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                foreach (var clientDTO in clientDTOs)
                {
                    var groupDTO = await groupService.FindAsync(new GroupDTO { Id = clientDTO.GroupId });
                    if (!groupDTO.Schedules.Any(x => x.EndTime > Now))
                    {
                        continue;
                    }
                    var groupModel = Mapper.Map<GroupViewModel>(groupDTO);
                    groupModel.IsEnabledLinks = false;

                    currentClientsModel.Add(new CurrentClientViewModel
                    {
                        Id = clientDTO.Id,
                        PaymentDate = clientDTO.PaymentDate,
                        Group = groupModel
                    });
                }
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return View(currentClientsModel);
        }

        [Authorize(Roles = nameof(RoleEnum.Client))]
        public async Task<ActionResult> Pay(int clientId)
        {
            try
            {
                var clientDTO = await clientService.FindAsync(new ClientDTO { Id = clientId });
                if (clientDTO.PaymentDate.HasValue)
                {
                    return RedirectToAction("InternalServerError", "Error");
                }
                clientDTO.PaymentDate = Now;
                clientService.Update(clientDTO);
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int groupId)
        {
            try
            {
                GroupDTO groupDTO = await groupService.FindAsync(new GroupDTO { Id = groupId });

                if (IsNullOrEmpty(User.Identity.Name))
                {
                    return RedirectToAction("Forbidden", "Error");
                }

                UserDTO userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                if (userDTO == null)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                var clientDTOs = clientService.Find(clientDTO => clientDTO.GroupId == groupDTO.Id && clientDTO.UserId == userDTO.Id);
                if (clientDTOs.Count > 0)
                {
                    return RedirectToAction("Index");
                }

                OperationDetails operationDetails = await clientService.CreateAsync(new ClientDTO { GroupId = groupDTO.Id, UserId = userDTO.Id });
                if (!operationDetails.IsSucceeded)
                {
                    return RedirectToAction("InternalServerError", "Error");
                }

                if (!userService.IsInRole(userDTO, RoleEnum.Client))
                {
                    await userService.AddToRoleAsync(userDTO, RoleEnum.Client);
                    IdentityResult result = await userService.UpdateSecurityStampAsync(userDTO);
                    if (result != null && result.Succeeded)
                    {
                        ClaimsIdentity claimsIdentity = await userService.AuthenticateAsync(userDTO);
                        if (claimsIdentity == null)
                        {
                            return RedirectToAction("InternalServerError", "Error");
                        }
                        AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                        AuthenticateResult authenticateResult = await AuthenticationManager.AuthenticateAsync(DefaultAuthenticationTypes.ApplicationCookie);
                        AuthenticationManager.SignIn(authenticateResult.Properties, claimsIdentity);
                    }
                    else
                    {
                        return RedirectToAction("InternalServerError", "Error");
                    }
                }
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return RedirectToAction("Index");
        }
    }
}

FitnessCenter.WEB/Controllers/Roles/TrainerController.cs
using AutoMapper;
using FitnessCenter.BLL.DTOs;
using FitnessCenter.CrossCutting.Enumerations;
using FitnessCenter.CrossCutting.Interfaces.BLL;
using FitnessCenter.WEB.ViewModels;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using static System.String;

namespace FitnessCenter.WEB.Controllers.Roles
{
    [Authorize]
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class TrainerController : Controller
    {
        private readonly IGroupService<GroupDTO> groupService;
        private readonly ITrainerService<TrainerDTO> trainerService;
        private readonly IUserService<UserDTO, string> userService;

        public TrainerController
        (
            IGroupService<GroupDTO> groupService,
            ITrainerService<TrainerDTO> trainerService,
            IUserService<UserDTO, string> userService
        )
        {
            this.groupService = groupService;
            this.trainerService = trainerService;
            this.userService = userService;
        }

        [Authorize(Roles = nameof(RoleEnum.Trainer))]
        public async Task<ActionResult> Index()
        {
            TrainerViewModel model = null;

            try
            {
                if (IsNullOrEmpty(User.Identity.Name))
                {
                    return RedirectToAction("InternalServerError", "Error");
                }

                var userDTO = await userService.FindAsync(new UserDTO { Email = User.Identity.Name });
                if (userDTO == null)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                var trainerDTOs = trainerService.Find(x => x.UserId == userDTO.Id);
                if (trainerDTOs.Count == 0)
                {
                    return RedirectToAction("NotFound", "Error");
                }

                model = Mapper.Map<TrainerViewModel>(trainerDTOs.First());
            }
            catch
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            return View(model);
        }

        [Authorize(Roles = nameof(RoleEnum.Trainer))]
        public async Task<ActionResult> GetGroup(int groupId)
        {
            var group = await groupService.FindAsync(new GroupDTO { Id = groupId });
            var model = Mapper.Map<GroupViewModel>(group);

            return View(model);
        }
    }
}

FitnessCenter.WEB/Views/Home/Index.cshtml
@using FitnessCenter.CrossCutting.Enumerations
@using FitnessCenter.CrossCutting.Resources
@using FitnessCenter.WEB.ViewModels

@model UserViewModel

@{
    ViewBag.Title = Resource.HomePage;
}

@section Main {
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xl-3 d-none d-md-block">
                @if (Model == default(UserViewModel) || Model.Roles.Count() <= 1)
                {
                    <div class="bottom-border-common"></div>
                }
            </div>
            <div class="col-12 col-md-8 col-xl-9">
                <div class="bottom-border-accent">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-lg-7 col-xl-8">
                                <div class="notification">
                                    @Resource.DemoResource
                                </div>
                            </div>
                            <div class="col-lg-5 col-xl-4 d-none d-lg-block">
                                <div class="address">
                                    @Resource.CenterAddress
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-4 col-xl-3">
            <div class="container">
                <div class="row">
                    <div class="col-6 col-md-12">
                        @if (Model != default(UserViewModel) && Model.Roles.Count() > 1)
                        {
                            <ul class="navigation navigation-roles">
                                @foreach (var role in Model.Roles)
                                {
                                    if (role == RoleEnum.User)
                                    {
                                        continue;
                                    }

                                    <li>
                                        @switch (role)
                                        {
                                            case RoleEnum.Administrator:
                                                @Html.ActionLink(@Resource.Administrator, "Index", "Administrator")
                                                break;
                                            case RoleEnum.Client:
                                                @Html.ActionLink(@Resource.Client, "Index", "Client")
                                                break;
                                            case RoleEnum.Trainer:
                                                @Html.ActionLink(@Resource.Trainer, "Index", "Trainer")
                                                break;
                                            default:
                                                break;
                                        }
                                    </li>
                                }
                            </ul>
                        }
                        else
                        { 
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 d-md-none">
                                        <div class="slogan-large">
                                            @Resource.Slogan
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <div class="col-6 col-md-12">
                        <div class="expand">
                            @if (Model == default(UserViewModel))
                            {
                                <img src="@Url.Content("~/FrontEnd/src/assets/images/sideBar.jpg")" />
                            }
                            else
                            {
                                <div class="title">
                                    @Model.Name
                                </div>
                                @Html.Raw($"<img src=\"{((Model.Photo == null || Model.Photo.Count() == 0) ? Url.Content("~/FrontEnd/src/assets/images/person.png") : $"data:image/jpeg;base64,{Convert.ToBase64String((byte[])Model.Photo)}")}\" class=\"rounded-circle img-indent-circle\" />")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xl-6 d-none d-md-block">
            <div class="expand">
                <img src="@Url.Content("~/FrontEnd/src/assets/images/main.jpg")" />
            </div>
        </div>
        <div class="col-xl-3 d-none d-xl-block">
            <div class="slogan-huge">
                @Resource.Slogan
            </div>
        </div>
    </div>
</div>
<div id="actualGroups">
</div>
<div id="actualGroupsPagination">
</div>
<div id="selectedGroup">
</div>